<?php
$this->headtitle($this->translate("Páginas"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li class="active"><?php echo $this->translate("Páginas") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<div class="row">
	<div class="col-lg-10"></div>
	<div class="col-lg-2">
		<a href="<?php echo $this->url("page/new")?>"
			class="btn btn-primary"><i class="fa fa-file-o"></i> <?php echo $this->translate("Nova Página")?></a>
	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading"> <?php echo $this->translate("Páginas")?></header>
			<table class="table table-striped table-advance table-hover">
				<thead>
					<tr>
						<th><i class="fa fa-file-text"></i> <?php echo $this->translate("Página")?></th>
						<th><i class="fa fa-file-text-o"></i> <?php echo $this->translate("Descrição")?></th>
						<th><i class="fa fa-circle-thin"></i> <?php echo $this->translate("Status")?></th>
						<th><i class="fa fa-edit"></i> <?php echo $this->translate("Ações")?></th>
					</tr>
				</thead>
				<tbody>
				<?php
    
    foreach ($pages as $page) {
        if ($page->active) {
            $status = $this->translate("Ativo");
            $statusClass = "success";
        } else {
            $status = $this->translate("Inativo");
            $statusClass = "danger";
        }
        ?>
					<tr>
						<td><?php echo $page->title; ?></td>
						<td><?php echo $page->description; ?></td>
						<td><span
							class="label label-<?php echo $statusClass; ?> label-mini"><?php echo $status; ?></span></td>
						<td>
							<a
							href="<?php echo $this->url("page/edit", array("id"=>$page->idPage))?>"
							class="btn btn-primary btn-xs"> <i class="fa fa-pencil"></i>
						</a>
							<button data-toggle="modal" href="#delete-<?php echo $page->idPage; ?>"
								class="btn btn-danger btn-xs">
								<i class="fa fa-trash-o "></i>
							</button>
						</td>
					</tr>
					<!-- EXCLUSION MODAL -->
					<div class="modal fade" id="delete-<?php echo $page->idPage; ?>" tabindex="-1" role="dialog"
						aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal"
										aria-hidden="true">&times;</button>
									<h4 class="modal-title"><?php echo $this->translate("Desejas realmente excluir?")?></h4>
								</div>
								<div class="modal-body"><?php echo $this->translate("Você realmente deseja excluir <strong>".$page->title."</strong> e todo o conteúdo relacionado com essa página?")?></div>
								<div class="modal-footer">
									<button data-dismiss="modal" class="btn btn-default"
										type="button"><?php echo $this->translate("Cancelar")?></button>
									<a href="<?php echo $this->url("page/delete", array("id"=>$page->idPage))?>" class="btn btn-danger" type="button"><?php echo $this->translate("Excluir")?></a>
								</div>
							</div>
						</div>
					</div>
					<!-- END OF EXCLUSION MODAL -->
					<?php } ?>
				</tbody>
			</table>
		</section>
	</div>
</div>
