<?php 
$this->headtitle($this->translate("Alterar Website"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("website")?>"><?php echo $this->translate("Websites") ?></a></li>
			<li class="active"><?php echo $this->translate("Alterar") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php 
if($message["flag"]>0){
    if($message["flag"]==1){
        $class = "success";
    }else{
        $class = "danger";
    }
    ?>
    <div class="alert alert-<?php echo $class; ?> alert-block fade in">
    	<button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>
    	<p><?php echo $message["message"]?></p>
    </div>
    <?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
                              <ul class="nav nav-tabs">
                                  <li>
                                      <a href="<?php echo $this->url("website/edit", array("id"=>$website->idWebsite))?>"><?php echo $this->translate("Editar Website")?></a>
                                  </li>
                                  <li class="active">
                                      <a data-toggle="tab" href="#"><?php echo $this->translate("Módulos")?></a>
                                  </li>
                                  <li>
                                      <a href="<?php echo $this->url("website/edit-users", array("id"=>$website->idWebsite))?>"><?php echo $this->translate("Usuários")?></a>
                                  </li>
                                  <li class="">
                                      <a href="<?php echo $this->url("website/settings", array("id"=>$website->idWebsite))?>"><?php echo $this->translate("Configurações")?></a>
                                  </li>
                              </ul>
                          </header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="website_modules">
	                <input type="hidden" name="idWebsite" value="<?php echo $website->idWebsite; ?>">
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Módulos")?></label>
						<div class="col-sm-10">
							<table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th><i class="fa fa-check"></i></th>
                                    <th><i class="fa fa-cube"></i> <?php echo $this->translate("Módulo") ?></th>
                                    <th><i class="fa fa-info-circle"></i> <?php echo $this->translate("Descrição") ?></th>
                                </tr>
                            </thead>
                            <tbody>
							<?php
							$modulesAlreadySelected = array();
							foreach($modulesSelected as $mSelected){
							    $modulesAlreadySelected[] = $mSelected->system_module_idModule;
							}
							
							foreach($modules as $module){ ?>
							<tr>
								<td><input type="checkbox" name="modules[]" <?php if(in_array($module->idModule, $modulesAlreadySelected)){ echo "checked"; } ?> value="<?php echo $module->idModule; ?>" /></td>
								<td><?php echo $module->name; ?></td>
								<td><?php echo $module->description; ?></td>
							</tr>
							<?php } ?>
							</tbody>
							</table>
						</div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;<button type="submit" class="btn btn-info"><?php echo $this->translate("Alterar")?></button>
						&nbsp;<a href="<?php echo $this->url("website")?>" class="btn btn-danger"><?php echo $this->translate("Voltar")?></a>
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
<?php 
//$this->headlink()->prependStylesheet($this->basePath('css/style-responsive.css'));
$this->headScript()->prependFile($this->basePath("js/validators/website.js"));
?>
