<?php 
$this->headtitle($this->translate("Novo Website"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("website")?>"><?php echo $this->translate("Websites") ?></a></li>
			<li class="active"><?php echo $this->translate("Novo") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php 
if($message["flag"]>0){
    if($message["flag"]==1){
        $class = "success";
    }else{
        $class = "danger";
    }
    ?>
    <div class="alert alert-<?php echo $class; ?> alert-block fade in">
    	<button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>
    	<p><?php echo $message["message"]?></p>
    </div>
    <?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
                              <ul class="nav nav-tabs">
                                  <li class="active">
                                      <a data-toggle="tab" href="#"><?php echo $this->translate("Novo Website")?></a>
                                  </li>
                                  <li class="">
                                      <a><?php echo $this->translate("Módulos")?></a>
                                  </li>
                                  <li class="">
                                      <a><?php echo $this->translate("Usuários")?></a>
                                  </li>
                                  <li class="">
                                      <a><?php echo $this->translate("Configurações")?></a>
                                  </li>
                              </ul>
                          </header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="website">
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Empresa*")?></label>
						<div class="col-sm-10">
                            <select class="form-control m-bot15" name="company_id">
								<?php 
								foreach($companies as $company){ ?>
								<option value="<?php echo $company->idCompany; ?>"><?php echo $company->name; ?></option>
								<?php } ?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Nome*")?></label>
						<div class="col-sm-10">
                                                    <input type="text" class="form-control" name="name" id="name" maxlength="60" value="<?php echo $website->name; ?>" >
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Ativo")?></label>
						<div class="col-sm-10">
								<input type="checkbox" name="status" value="1" checked data-toggle="switch" /> 
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Módulos")?></label>
						<div class="col-sm-10">
							<table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th><i class="fa fa-check"></i></th>
                                    <th><i class="fa fa-cube"></i> <?php echo $this->translate("Módulo") ?></th>
                                    <th><i class="fa fa-info-circle"></i> <?php echo $this->translate("Descrição") ?></th>
                                </tr>
                            </thead>
                            <tbody>
							<?php foreach($modules as $module){ ?>
							<tr>
								<td><input type="checkbox" name="modules[]" value="<?php echo $module->idModule; ?>" /></td>
								<td><?php echo $module->name; ?></td>
								<td><?php echo $module->description; ?></td>
							</tr>
							<?php } ?>
							</tbody>
							</table>
						</div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;<button type="submit" class="btn btn-info"><?php echo $this->translate("Cadastrar")?></button>
						&nbsp;<a href="<?php echo $this->url("website")?>" class="btn btn-danger"><?php echo $this->translate("Cancelar")?></a>
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
<?php 
//$this->headlink()->prependStylesheet($this->basePath('css/style-responsive.css'));
$this->headScript()->prependFile($this->basePath("js/validators/website.js"));
?>
