<?php
$this->headtitle($this->translate("Alterar Website"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("website")?>"><?php echo $this->translate("Websites") ?></a></li>
			<li class="active"><?php echo $this->translate("Alterar") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php
if ($message["flag"] > 0) {
    if ($message["flag"] == 1) {
        $class = "success";
    } else {
        $class = "danger";
    }
    ?>
<div class="alert alert-<?php echo $class; ?> alert-block fade in">
	<button data-dismiss="alert" class="close close-sm" type="button">
		<i class="fa fa-times"></i>
	</button>
	<p><?php echo $message["message"]?></p>
</div>
<?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
				<ul class="nav nav-tabs">
					<li><a
						href="<?php echo $this->url("website/edit", array("id"=>$website->idWebsite))?>"><?php echo $this->translate("Editar Website")?></a>
					</li>
					<?php if($logedUser["idCompany"]==1){ ?>
					<li><a
						href="<?php echo $this->url("website/edit-modules", array("id"=>$website->idWebsite))?>"><?php echo $this->translate("Módulos")?></a>
					</li>
					<?php } ?>
					<li class="active"><a href="#"><?php echo $this->translate("Usuários")?></a>
					</li>
					<li><a href="<?php echo $this->url("website/settings", array("id"=>$website->idWebsite))?>"><?php echo $this->translate("Configurações")?></a>
					</li>
				</ul>
			</header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post"
					id="website_users">
					<input type="hidden" name="company_website_idWebsite"
						value="<?php echo $website->idWebsite; ?>">
					<div class="form-group">
						<label class="col-sm-4 col-sm-4 control-label"><?php echo $this->translate("Adicionar Usuário ao Site")?></label>
						<div class="col-sm-6">
							<select class="form-control m-bot15" name="company_user_idUser">
								<?php
        foreach ($users as $user) {
            ?>
								<option value="<?php echo $user->idUser; ?>"><?php echo $user->name; ?></option>
								<?php } ?>
							</select>
						</div>
						<div class="col-sm-2">
							<button type="submit" class="btn btn-info"><?php echo $this->translate("Adicionar")?></button>
						</div>
					</div>
				</form>
				<hr>
				<div class="form-group">
					<div class="col-sm-12">
						<table class="table table-striped table-advance table-hover">
							<thead>
								<tr>
									<th><i class="fa fa-user"></i> <?php echo $this->translate("Usuário") ?></th>
									<th><i class="fa fa-edit"></i> <?php echo $this->translate("Ação") ?></th>
								</tr>
							</thead>
							<tbody>
							<?php
    foreach ($usersRelationship as $user) {
        ?>
							<tr>
									<td><?php echo $user->userName; ?></td>
									<td><a
										href="<?php echo $this->url("user/edit", array("id"=>$user->company_user_idUser))?>"
										class="btn btn-warning btn-xs"> <i class="fa fa-pencil"></i>
									</a>
										<button data-toggle="modal"
											href="#delete-<?php echo $user->company_user_idUser; ?>"
											class="btn btn-danger btn-xs">
											<i class="fa fa-trash-o "></i>
										</button></td>
									<div class="modal fade"
										id="delete-<?php echo $user->company_user_idUser; ?>" tabindex="-1"
										role="dialog" aria-labelledby="myModalLabel"
										aria-hidden="true">
										<div class="modal-dialog">
											<div class="modal-content">
												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal"
														aria-hidden="true">&times;</button>
													<h4 class="modal-title"><?php echo $this->translate("Desejas realmente remover o usuário deste website?") ?></h4>
												</div>
												<div class="modal-body"><?php echo $this->translate("Você realmente deseja remover a permissão de acesso do usuário <strong>" . $user->userName . "</strong> para este website?") ?></div>
												<div class="modal-footer">
													<button data-dismiss="modal" class="btn btn-default"
														type="button"><?php echo $this->translate("Cancelar") ?></button>
													<a
														href="<?php echo $this->url("website/edit-users", array("id" => $website->idWebsite, "idUser"=>$user->company_user_idUser)); ?>"
														class="btn btn-danger" type="button"><?php echo $this->translate("Excluir") ?></a>
												</div>
											</div>
										</div>
									</div>
								</tr>
							<?php } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</section>
	</div>
</div>
<?php
// $this->headlink()->prependStylesheet($this->basePath('css/style-responsive.css'));
$this->headScript()->prependFile($this->basePath("js/validators/website.js"));
?>
