<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Page\Module'                        => __DIR__ . '/Module.php',
    'Page\Controller\PageController' => __DIR__ . '/src/Page/Controller/PageController.php',
);
