<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Website\Module'                        => __DIR__ . '/Module.php',
    'Website\Controller\WebsiteController' => __DIR__ . '/src/Website/Controller/WebsiteController.php',
    'WebsiteTest\Framework\TestCase'        => __DIR__ . '/tests/Website/Framework/TestCase.php',
    'WebsiteTest\SampleTest'                => __DIR__ . '/tests/Website/SampleTest.php',
);
