<?php 
$this->headtitle($this->translate("Editar Empresa"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("company")?>"><?php echo $this->translate("Empresas") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php 
if($message["flag"]>0){
    if($message["flag"]==1){
        $class = "success";
    }else{
        $class = "danger";
    }
    ?>
    <div class="alert alert-<?php echo $class; ?> alert-block fade in">
    	<button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>
    	<p><?php echo $message["message"]?></p>
    </div>
    <?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading"> <?php echo $this->translate("Nova Empresa")?> </header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="company">
					<input type="hidden" name="idCompany" value="<?php echo $copany->idCompany; ?>">
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Nome*")?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="name" maxlength="120" id="name" value="<?php echo $copany->name; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Ativo")?></label>
						<div class="col-sm-10">
								<input type="checkbox" name="status" value="1" 
								<?php echo ($copany->status) ? "checked" : "" ?>
								data-toggle="switch" /> 
						</div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;<button type="submit" class="btn btn-info"><?php echo $this->translate("Alterar")?></button>
						&nbsp;<a href="<?php echo $this->url("company")?>" class="btn btn-danger"><?php echo $this->translate("Cancelar")?></a>
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
<?php 
//$this->headlink()->prependStylesheet($this->basePath('css/style-responsive.css'));
$this->headScript()->prependFile($this->basePath("js/validators/company.js"));
?>
