<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Conversor\Module'                        => __DIR__ . '/Module.php',
    'Conversor\Controller\ConversorController' => __DIR__ . '/src/Conversor/Controller/ConversorController.php',
    'ConversorTest\Framework\TestCase'        => __DIR__ . '/tests/Conversor/Framework/TestCase.php',
    'ConversorTest\SampleTest'                => __DIR__ . '/tests/Conversor/SampleTest.php',
);
