<?php 
$this->headtitle($this->translate("Editar Categoria"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("product")?>"><?php echo $this->translate("Produtos") ?></a></li>
			<li><a href="<?php echo $this->url("product/category")?>"><?php echo $this->translate("Categorias") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php 
if($message["flag"]>0){
    if($message["flag"]==1){
        $class = "success";
    }else{
        $class = "danger";
    }
    ?>
    <div class="alert alert-<?php echo $class; ?> alert-block fade in">
    	<button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>
    	<p><?php echo $message["message"]?></p>
    </div>
    <?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
              <ul class="nav nav-tabs">
                  <li class="active">
                      <a data-toggle="tab" href="#"><?php echo $this->translate("Editar Página")?></a>
                  </li>
                  <?php foreach ($websiteLanguages as $language){                                      ?>
                  <li class="">
                      <a href="<?php echo $this->url("product/category/edit-language", array("id"=>$category->idCategory, "idLanguage"=>$language->language_id))?>"><?php echo $language->name; ?></a>
                  </li>
                  <?php } ?>
              </ul>
          </header>
    		<div class="panel-body">
    			<form class="form-horizontal tasi-form" method="post" id="category">
    				<div class="form-group">
						<label class="col-sm-2 control-label"><?php echo $this->translate("É uma subcategoria?")?></label>
						<div class="col-sm-10">
							<label><input type="radio" name="sub" class="sub" value="1" data-toggle="switch" <?php if($category->subcategory_id!=null){ ?>checked="checked"<?php } ?> /> <?php echo $this->translate("Sim")?></label>
							<label><input type="radio" name="sub" class="sub" value="2" data-toggle="switch" <?php if($category->subcategory_id==null){ ?>checked="checked"<?php } ?>  /> <?php echo $this->translate("Não")?></label>
						</div>
					</div>
					<div class="form-group" id="subcategory">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Categoria mãe")?></label>
						<div class="col-sm-10">
                        	<select name="subcategory_id" class="form-control">
                        		<?php foreach($categories as $categoryMother){ ?>
								<option value="<?php echo $categoryMother->idCategory; ?>" <?php if($category->subcategory_id==$categoryMother->idCategory){ echo "selected"; } ?>><?php echo $categoryMother->title;?></option>
								<?php } ?>
							</select>
						</div>
					</div>
    				<div class="form-group">
    					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Título*")?></label>
    					<div class="col-sm-10">
                        	<input type="text" class="form-control" name="title" id="title" maxlength="60" value="<?php echo $category->title; ?>" >
    					</div>
    				</div>
    				<div class="form-group">
    					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Ativo")?></label>
    					<div class="col-sm-10">
    							<input type="checkbox" name="active" value="1" <?php if($category->active){ ?>checked<?php } ?> data-toggle="switch" /> 
    					</div>
    				</div>
    				<div class="form-group">
    					&nbsp;&nbsp;<button type="submit" class="btn btn-info"><?php echo $this->translate("Salvar")?></button>
    					&nbsp;<a href="<?php echo $this->url("product/category")?>" class="btn btn-danger"><?php echo $this->translate("Voltar")?></a>
    				</div>
    			</form>
    		</div>
		</section>
	</div>
</div>
<?php 
$this->headScript()->prependFile($this->basePath("js/validators/category.js"));
$this->headscript()->captureStart();
echo <<<JS
$(document).ready(function(){
    $('#subcategory').hide('true');
    $('.sub').change(function(){
        console.log("Subcategory");
        $('#subcategory').hide('true');
        if(this.value==1){
            $('#subcategory').fadeIn('slow');
        }else{
            $('#subcategory').hide('true');
	    }
    });
});
JS;
$this->headscript()->captureEnd();

if($category->subcategory_id!=null){
    $this->headscript()->captureStart();
echo <<<JS
$(document).ready(function(){
    $('#subcategory').fadeIn('slow');
});
JS;
    $this->headscript()->captureEnd();

}
?>
