<?php
$this->headtitle($this->translate("Editar Categoria"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("product")?>"><?php echo $this->translate("Produtos") ?></a></li>
			<li><a href="<?php echo $this->url("product/category")?>"><?php echo $this->translate("Categorias") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar Idioma") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php
if ($message["flag"] > 0) {
    if ($message["flag"] == 1) {
        $class = "success";
    } else {
        $class = "danger";
    }
    ?>
<div class="alert alert-<?php echo $class; ?> alert-block fade in">
	<button data-dismiss="alert" class="close close-sm" type="button">
		<i class="fa fa-times"></i>
	</button>
	<p><?php echo $message["message"]?></p>
</div>
<?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
				<ul class="nav nav-tabs">
					<li><a href="<?php echo $this->url("product/category/edit", array("id"=>$category->idCategory))?>"><?php echo $this->translate("Editar Página")?></a>
					</li>
                      <?php foreach ($websiteLanguages as $language){                                      ?>
                      <li
						<?php if($language->language_id==$idLanguage){?> class="active"
						<?php } ?>><a
						href="<?php echo $this->url("product/category/edit-language", array("id"=>$category->idCategory, "idLanguage"=>$language->language_id))?>"><?php echo $language->name; ?></a>
					</li>
                      <?php } ?>
                  </ul>
			</header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="category">
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Título*")?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="title" id="title"
								maxlength="60"
								value="<?php echo ($categoryLanguage->title) ? $categoryLanguage->title : $category->title; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Slug*")?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="slug" id="slug"
								maxlength="150"
								value="<?php echo ($categoryLanguage->slug) ? $categoryLanguage->slug : ""; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Ativo")?></label>
						<div class="col-sm-10">
							<input type="checkbox" name="active" value="1"
								<?php if($categoryLanguage->active){ ?> checked <?php } ?>
								data-toggle="switch" />
						</div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;
						<button type="submit" class="btn btn-info"><?php echo $this->translate("Salvar")?></button>
						&nbsp;<a href="<?php echo $this->url("product/category")?>"
							class="btn btn-danger"><?php echo $this->translate("Voltar")?></a>
					</div>
				</form>
			</div>
		</section>
	</div>
</div>

<?php
$this->headScript()->prependFile($this->basePath("js/validators/category.js"));
$this->inlinescript()->captureStart();
echo <<<JS

$("#title").keyup(function(){
    var Text = $(this).val();
    Text = Text.toLowerCase();
    Text = Text.replace(/[^a-zA-Z0-9]+/g,'-');
    $("#slug").val(Text);        
});

JS;
$this->inlinescript()->captureEnd();
?>
