<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Article\Module'                        => __DIR__ . '/Module.php',
    'Article\Controller\ArticleController' => __DIR__ . '/src/Article/Controller/ArticleController.php',
);
