<?php
$this->headtitle($this->translate("Alterar Usuário"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("user") ?>"><?php echo $this->translate("Usuários") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php
if ($message["flag"] > 0) {
    if ($message["flag"] == 1) {
        $class = "success";
    } else {
        $class = "danger";
    }
    ?>
<div class="alert alert-<?php echo $class; ?> alert-block fade in">
	<button data-dismiss="alert" class="close close-sm" type="button">
		<i class="fa fa-times"></i>
	</button>
	<p><?php echo $message["message"] ?></p>
</div>
<?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
				<ul class="nav nav-tabs">
					<li class="active"><a data-toggle="tab" href="#"><?php echo $this->translate("Editar Usuário")?></a>
					</li>
					<li class=""><a
						href="<?php echo $this->url("user/edit-permissions", array("id"=>$user->idUser))?>"><?php echo $this->translate("Permissões")?></a>
					</li>
					<li class=""><a
						href="<?php echo $this->url("user/edit-password", array("id"=>$user->idUser))?>"><?php echo $this->translate("Alterar Senha")?></a>
					</li>
				</ul>
			</header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="user">
					<input type="hidden" name="idUser"
						value="<?php echo $user->idUser; ?>">
					<?php if(count($companies)>0){ ?>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Empresa*") ?></label>
						<div class="col-sm-10">
							<select class="form-control m-bot15" name="company_id">
                                <?php foreach ($companies as $company) { ?>
                                    <option
									value="<?php echo $company->idCompany; ?>"
									<?php if ($user->company_id == $company->idCompany) { ?>
									selected=<?php } ?>><?php echo $company->name; ?></option>
                                <?php } ?>
                            </select>
						</div>
					</div>
					<?php } ?>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Tipo de Usuário*")?></label>
						<div class="col-sm-10">
                                <select class="form-control m-bot15" name="type">
                                <?php if(count($companies)>0){ //If loged user it's a tecnician?>
									<option value="1"><?php echo $this->translate("Técnico")?></option>
								<?php } ?>
                            		<option value="2" <?php if($user->type==2){ ?>selected="selected"<?php } ?>><?php echo $this->translate("Administrador")?></option>
                            		<option value="3" <?php if($user->type==3){ ?>selected="selected"<?php } ?>><?php echo $this->translate("Vendedor")?></option>

							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Nome*") ?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="name" id="name"
								maxlength="60" value="<?php echo $user->name; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Email*") ?></label>
						<div class="col-sm-10">
							<input type="email" class="form-control" name="email" id="email"
								maxlength="150" value="<?php echo $user->email; ?>">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Ativo") ?></label>
						<div class="col-sm-10">
							<input type="checkbox" name="status" value="1"
								<?php if ($user->status) { ?> checked <?php } ?>
								data-toggle="switch" />
						</div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;
						<button type="submit" class="btn btn-info"><?php echo $this->translate("Alterar") ?></button>
						&nbsp;<a href="<?php echo $this->url("user") ?>"
							class="btn btn-danger"><?php echo $this->translate("Cancelar") ?></a>
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
<?php
// $this->headlink()->prependStylesheet($this->basePath('css/style-responsive.css'));
$this->headScript()->prependFile($this->basePath("js/validators/user_edit.js"));
?>
