<?php
$this->headtitle($this->translate("Alterar Usuário"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("user") ?>"><?php echo $this->translate("Usuários") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php
if ($message["flag"] > 0) {
    if ($message["flag"] == 1) {
        $class = "success";
    } else {
        $class = "danger";
    }
    ?>
<div class="alert alert-<?php echo $class; ?> alert-block fade in">
	<button data-dismiss="alert" class="close close-sm" type="button">
		<i class="fa fa-times"></i>
	</button>
	<p><?php echo $message["message"] ?></p>
</div>
<?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
				<ul class="nav nav-tabs">
					<li><a href="<?php echo $this->url("user/edit", array("id"=>$user->idUser))?>"><?php echo $this->translate("Editar Usuário")?></a>
					</li>
					<li class="active"><a data-toggle="tab" 
						href="<?php echo $this->url("user/edit-permissions", array("id"=>$user->idUser))?>"><?php echo $this->translate("Permissões")?></a>
					</li>
					<li><a
						href="<?php echo $this->url("user/edit-password", array("id"=>$user->idUser))?>"><?php echo $this->translate("Alterar Senha")?></a>
					</li>
				</ul>
			</header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="user">
					<input type="hidden" name="idUser"
						value="<?php echo $user->idUser; ?>">
					<div class="form-group">
						<div class="col-sm-12">
							<h3><?php echo $user->name; ?></h3>
						</div>
					</div>
					<?php 
					foreach($websites as $website){
					    $websiteData = $website["website"];
					    $websiteModules = $website["modules"];
					    $permissions = $website["permissions"];
					    
					?>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Website") ?></label>
						<div class="col-sm-10">
							<?php echo $websiteData->websiteName; ?>
                        </div>
                        <div class="col-sm-10">
							<table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th><i class="fa fa-cube"></i> <?php echo $this->translate("Módulo") ?></th>
                                    <th><i class="fa fa-plus-circle"></i> <?php echo $this->translate("Cadastro") ?></th>
                                    <th><i class="fa fa-pencil"></i> <?php echo $this->translate("Edição") ?></th>
                                    <th><i class="fa fa-trash"></i> <?php echo $this->translate("Exclusão") ?></th>
                                </tr>
                            </thead>
                            <tbody>
							<?php
							$modulePermissions = iterator_to_array($permissions);
								
							foreach($websiteModules as $module){ 
							    $insert = 0;
							    $edit = 0;
							    $delete = 0;
							    foreach($modulePermissions as $permission){
							        if($permission->website_module_idModule == $module->system_module_idModule){
							            $insert = $permission->insertP;
							            $edit = $permission->editP;
							            $delete = $permission->deleteP;
							            break;
							        }
							    }
							?>
							<tr>
								<td><?php echo $module->moduleName; ?></td>
								<td><input type="checkbox" name="insert[<?php echo $websiteData->company_website_idWebsite; ?>-<?php echo $module->system_module_idModule; ?>]" value="1" <?php echo ($insert) ? "checked" : ""?>></td>
								<td><input type="checkbox" name="edit[<?php echo $websiteData->company_website_idWebsite; ?>-<?php echo $module->system_module_idModule; ?>]" value="1" <?php echo ($edit) ? "checked" : ""?>></td>
								<td><input type="checkbox" name="delete[<?php echo $websiteData->company_website_idWebsite; ?>-<?php echo $module->system_module_idModule; ?>]" value="1" <?php echo ($delete) ? "checked" : ""?>></td>
							</tr>
							<?php } ?>
							</tbody>
							</table>
                        </div>
					</div>
					<?php } ?>
					<div class="form-group">
						&nbsp;&nbsp;
						<button type="submit" class="btn btn-info"><?php echo $this->translate("Alterar") ?></button>
						&nbsp;
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
