<?php
$this->headtitle($this->translate("Alterar Usuário"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("user") ?>"><?php echo $this->translate("Usuários") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php
if ($message["flag"] > 0) {
    if ($message["flag"] == 1) {
        $class = "success";
    } else {
        $class = "danger";
    }
    ?>
<div class="alert alert-<?php echo $class; ?> alert-block fade in">
	<button data-dismiss="alert" class="close close-sm" type="button">
		<i class="fa fa-times"></i>
	</button>
	<p><?php echo $message["message"] ?></p>
</div>
<?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
				<ul class="nav nav-tabs">
					<li><a href="<?php echo $this->url("user/edit", array("id"=>$user->idUser))?>"><?php echo $this->translate("Editar Usuário")?></a>
					</li>
					<li class=""><a
						href="<?php echo $this->url("user/edit-permissions", array("id"=>$user->idUser))?>"><?php echo $this->translate("Permissões")?></a>
					</li>
					<li class="active"><a data-toggle="tab"
						href="<?php echo $this->url("user/edit-password", array("id"=>$user->idUser))?>"><?php echo $this->translate("Alterar Senha")?></a>
					</li>
				</ul>
			</header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="user">
					<input type="hidden" name="idUser"
						value="<?php echo $user->idUser; ?>">
						<div class="form-group">
						<div class="col-sm-12">
							<h3><?php echo $user->name; ?></h3>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Senha") ?></label>
						<div class="col-sm-10">
							<input type="password" class="form-control" name="password"
								id="password" maxlength="20">
                            <?php echo $this->translate("Mínimo 6 dígitos."); ?>
                        </div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Confirmar Senha") ?></label>
						<div class="col-sm-10">
							<input type="password" class="form-control"
								name="confirm_password" id="confirm_password" maxlength="20">
                        </div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;
						<button type="submit" class="btn btn-info"><?php echo $this->translate("Alterar") ?></button>
						&nbsp;
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
<?php
// $this->headlink()->prependStylesheet($this->basePath('css/style-responsive.css'));
$this->headScript()->prependFile($this->basePath("js/validators/user_edit_password.js"));
?>
