<?php
$this->headtitle($this->translate("Usuários"));
?>
<div class="row">
    <div class="col-lg-12">
        <!--breadcrumbs start -->
        <ul class="breadcrumb">
            <li><a href="<?php echo $this->url("application"); ?>"><i
                        class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
            <li class="active"><?php echo $this->translate("Usuários") ?></li>
        </ul>
        <!--breadcrumbs end -->
    </div>
</div>

<div class="row">
    <div class="col-lg-10"></div>
    <div class="col-lg-2">
    	<?php if($logedUserPermission->insertP && $ableToInsert){ ?>
        <a href="<?php echo $this->url("user/new") ?>"
           class="btn btn-primary"><i class="fa fa-plus"></i> <?php echo $this->translate("Novo Usuário") ?></a>
       <?php }else if($ableToInsert==false){
           echo $this->translate("Para adquirir licenças para novos usuários, entre em contato conosco.");
       }?>
    </div>
</div>
<br>
<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading"> <?php echo $this->translate("Usuários") ?></header>
            <div class="col-sm-12"> <?php 
            echo count($users).$this->translate(" de ").$companyData->max_users.$this->translate(" licenças de usuários.")?></div>
            <table class="table table-striped table-advance table-hover">
                <thead>
                    <tr>
                        <th><i class="fa fa-user"></i> <?php echo $this->translate("Usuário") ?></th>
                        <th><i class="fa fa-building"></i> <?php echo $this->translate("Empresa") ?></th>
                        <th><i class="fa fa-envelope"></i> <?php echo $this->translate("E-mail") ?></th>
                        <th><i class="fa fa-check-circle"></i> <?php echo $this->translate("Tipo") ?></th>
                        <th><i class="fa fa-check-circle"></i> <?php echo $this->translate("Status") ?></th>
                        <th><i class="fa fa-edit"></i> <?php echo $this->translate("Ações") ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($users as $user) {
                        if ($user->status) {
                            $status = $this->translate("Ativo");
                            $statusClass = "success";
                        } else {
                            $status = $this->translate("Inativo");
                            $statusClass = "danger";
                        }
                        ?>
                        <tr>
                            <td><a href="#"><?php echo $user->name; ?></a></td>
                            <td><a href="<?php echo $this->url("company/edit", array("id" => $user->company_id)); ?>"><?php echo $user->company; ?></a></td>
                            <td><?php echo $user->email; ?></td>
                            <td>
                            <?php 
                            switch($user->type){
                                case 1:
                                    echo "Técnico";
                                    break;
                                case 2:
                                    echo "Administrador";
                                    break;
                                case 3:
                                    echo "Vendedor";
                                    break;
                            }
                            ?>
                            </td>
                            <td><span
                                    class="label label-<?php echo $statusClass; ?> label-mini"><?php echo $status; ?></span></td>
                            <td>
                            	<?php if($logedUserPermission->editP){ ?>
                                <a href="<?php echo $this->url("user/edit-permissions", array("id"=>$user->idUser)); ?>" class="btn btn-warning btn-xs">
                                    <i class="fa fa-sitemap" title="<?php echo $this->translate("Permissões")?>"></i>
                                </a> 
                                <a
                                    href="<?php echo $this->url("user/edit", array("id" => $user->idUser)) ?>"
                                    class="btn btn-primary btn-xs"> <i class="fa fa-pencil" title="<?php echo $this->translate("Editar Usuário")?>"></i>
                                </a>
                                <?php } ?>
                                <?php if($logedUserPermission->deleteP){ ?>
                                <button data-toggle="modal" href="#delete-<?php echo $user->idUser; ?>"
                                        class="btn btn-danger btn-xs">
                                    <i class="fa fa-trash-o" title="<?php echo $this->translate("Excluir Usuário")?>"></i>
                                </button>
                                <?php } ?>
                            </td>
                        </tr>
                        <?php if($logedUserPermission->deleteP){ ?>
                        <!-- EXCLUSION MODAL -->
                    <div class="modal fade" id="delete-<?php echo $user->idUser; ?>" tabindex="-1" role="dialog"
                         aria-labelledby="myModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal"
                                            aria-hidden="true">&times;</button>
                                    <h4 class="modal-title"><?php echo $this->translate("Desejas realmente excluir?") ?></h4>
                                </div>
                                <div class="modal-body"><?php echo $this->translate("Você realmente deseja excluir <strong>" . $user->name . "</strong> e todo o conteúdo relacionado com este usuário?") ?></div>
                                <div class="modal-footer">
                                    <button data-dismiss="modal" class="btn btn-default"
                                            type="button"><?php echo $this->translate("Cancelar") ?></button>
                                    <a href="<?php echo $this->url("user/delete", array("id" => $user->idUser)) ?>" class="btn btn-danger" type="button"><?php echo $this->translate("Excluir") ?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END OF EXCLUSION MODAL -->
                    <?php } //End permission check?>
                <?php } ?>
                </tbody>
            </table>
        </section>
    </div>
</div>
