<?php
$this->headtitle($this->translate("Usuários do Website"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li class="active"><?php echo $this->translate("Usuários do Website") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<div class="panel-body">
				<h3><?php echo $this->translate("Website: ")?><?php foreach($website as $data) : echo $data->name; endforeach; ?>
        	</h3>
			</div>

		</section>
		<section class="panel">
			<div class="panel-body">
				<button data-toggle="modal" href="#change-website"
					class="btn btn-default">
					<i class="fa fa-retweet"></i> <?php echo $this->translate("Alterar Website") ?></button>
				<a href="<?php echo $this->url("website/new") ?>"
					class="btn btn-primary"><i class="fa fa-plus"></i> <?php echo $this->translate("Incluir Usuário") ?></a>
			</div>
		</section>
	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading"> <?php echo $this->translate("Usuários para o Website") ?></header>
			<table class="table table-striped table-advance table-hover">
				<thead>
					<tr>
						<th><i class="fa fa-user"></i> <?php echo $this->translate("Usuário") ?></th>
						<th><i class="fa fa-desktop"></i> <?php echo $this->translate("Webiste") ?></th>
						<th><i class="fa fa-edit"></i> <?php echo $this->translate("Ações") ?></th>
					</tr>
				</thead>
				<tbody>
                    <?php
                    foreach ($users as $user) {
                        if ($user->status) {
                            $status = $this->translate("Ativo");
                            $statusClass = "success";
                        } else {
                            $status = $this->translate("Inativo");
                            $statusClass = "danger";
                        }
                        ?>
                        <tr>
						<td><a href="#"><?php echo $user->userName; ?></a></td>
						<td><a
							href="<?php echo $this->url("company/edit", array("id" => $user->company_user_idUser)); ?>"><?php echo $user->company; ?></a></td>
						<td><span
							class="label label-<?php echo $statusClass; ?> label-mini"><?php echo $status; ?></span></td>
						<td><a
							href="<?php echo $this->url("website-user", array("idWebsite"=>$user->$user->company_user_idUser))?>"
							class="btn btn-warning btn-xs"> <i class="fa fa-users"></i>
						</a>
							<button data-toggle="modal"
								href="#delete-<?php echo $user->company_user_idUser; ?>"
								class="btn btn-danger btn-xs">
								<i class="fa fa-trash-o "></i>
							</button></td>
					</tr>
					<!-- EXCLUSION MODAL -->
					<div class="modal fade"
						id="delete-<?php echo $user->company_user_idUser; ?>"
						tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
						aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal"
										aria-hidden="true">&times;</button>
									<h4 class="modal-title"><?php echo $this->translate("Desejas realmente excluir?") ?></h4>
								</div>
								<div class="modal-body"><?php echo $this->translate("Você realmente deseja excluir <strong>" . $user->userName . "</strong> e todo o conteúdo relacionado com este website?") ?></div>
								<div class="modal-footer">
									<button data-dismiss="modal" class="btn btn-default"
										type="button"><?php echo $this->translate("Cancelar") ?></button>
									<a
										href="<?php echo $this->url("website/delete", array("id" => $user->company_user_idUser)); ?>"
										class="btn btn-danger" type="button"><?php echo $this->translate("Excluir") ?></a>
								</div>
							</div>
						</div>
					</div>
					<!-- END OF EXCLUSION MODAL -->
                <?php } ?>
                </tbody>
			</table>
		</section>
	</div>
</div>
<!-- CHANGE WEBSITE MODAL -->
<div class="modal fade" id="change-website" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title"><?php echo $this->translate("Desejas visualizar os usuários de qual website?") ?></h4>
			</div>
			<div class="modal-body">
									<?php
        foreach ($websites as $website) {
            ?>
									    <a
					href="<?php echo $this->url("website-user", array("idWebsite"=>$website->idWebsite))?>"
					class="btn btn-default btn-lg btn-block"><?php echo $website->name; ?></a><br>
									    <?php
        }
        ?>
								</div>
			<div class="modal-footer">
				<button data-dismiss="modal" class="btn btn-danger" type="button"><?php echo $this->translate("Cancelar") ?></button>
			</div>
		</div>
	</div>
</div>