<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Company\Module'                        => __DIR__ . '/Module.php',
    'Company\Controller\CompanyController' => __DIR__ . '/src/Company/Controller/CompanyController.php',
    'CompanyTest\Framework\TestCase'        => __DIR__ . '/tests/Company/Framework/TestCase.php',
    'CompanyTest\SampleTest'                => __DIR__ . '/tests/Company/SampleTest.php',
);
