<?php
$this->headtitle($this->translate("Banco de Imagens"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Banco de Imagens") ?></a></li>
			<li class="active"><?php echo $this->translate("Nova Imagem") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<!-- page start-->
<section class="panel">
	<header class="panel-heading"> <?php echo $this->translate("Arraste suas imagens")?></header>
	<div class="panel-body">
		<form action="<?php echo $this->url("images-database/upload"); ?>"
			class="dropzone">
		</form>
	</div>
	<div class="panel-body">
		<a class="btn btn-primary" href="<?php echo $this->url("images-database")?>"><i class="fa fa-list"></i> <?php echo $this->translate("Lista de imagens") ?></a>
	</div>
</section>
<!-- page end-->
<?php
$this->headLink()->prependStylesheet($this->basePath('assets/dropzone/css/dropzone.css'));
$this->headScript()->prependFile($this->basePath('assets/dropzone/dropzone.js'));
?>