<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Customer\Module'                        => __DIR__ . '/Module.php',
    'Customer\Controller\CustomerController' => __DIR__ . '/src/Customer/Controller/CustomerController.php',
);
