<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'WebsiteUser\Module'                        => __DIR__ . '/Module.php',
    'WebsiteUser\Controller\WebsiteUserController' => __DIR__ . '/src/WebsiteUser/Controller/WebsiteUserController.php',
    'WebsiteUserTest\Framework\TestCase'        => __DIR__ . '/tests/WebsiteUser/Framework/TestCase.php',
    'WebsiteUserTest\SampleTest'                => __DIR__ . '/tests/WebsiteUser/SampleTest.php',
);
