<?php
$this->headtitle($this->translate("Conversor de Exportadores"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li class="active"><?php echo $this->translate("Conversor de Exportadores") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<!--Advanced File Input start-->
<div class="row">
	<div class="col-md-12">
		<section class="panel">
			<header class="panel-heading">
				Conversor de Exportadores<span class="tools pull-right"> <a
					href="javascript:;" class="fa fa-chevron-down"></a> <a
					href="javascript:;" class="fa fa-times"></a>
				</span>
			</header>
			<div class="panel-body">
				<form action="" class="form-horizontal tasi-form" method="POST" enctype="multipart/form-data">
					<div class="form-group">
						<label class="control-label col-md-3">Converter de DOMÍNIO para EFFECTIVE </label>
						<div class="col-md-4">
							<input type="file" class="default" name="arquivo"  />
						</div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;&nbsp;<button type="submit" class="btn btn-default" >Converter</button>
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
<!--Advanced File Input end-->