  <?php
$this->headtitle($this->translate("Pipeline"));
?>
<div class="row">
    <div class="col-lg-12">
        <!--breadcrumbs start -->
        <ul class="breadcrumb">
            <li><a href="<?php echo $this->url("application"); ?>"><i
                        class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
            <li class="active"><?php echo $this->translate("Pipeline") ?></li>
        </ul>
        <!--breadcrumbs end -->
    </div>
</div>

  <!-- page start-->
  <div class="row-fluid" id="draggable_portlets">
      <div class="col-md-3 column sortable">
      	<h3><?php echo $this->translate("Prospects")?></h3>
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-default">
              <div class="panel-heading">Portlet 1</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-primary">
              <div class="panel-heading">Portlet 2</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-success">
              <div class="panel-heading">Portlet 3</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
      </div>
      <div class="col-md-3 column sortable">
    	  <h3><?php echo $this->translate("Proposta")?></h3>
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-warning">
              <div class="panel-heading">Portlet 4</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-danger">
              <div class="panel-heading">Portlet 5</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-info">
              <div class="panel-heading">Portlet 6</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
      </div>
      <div class="col-md-3 column sortable">
      	  <h3><?php echo $this->translate("Seguindo")?></h3>
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-default">
              <div class="panel-heading">Portlet 7</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-success">
              <div class="panel-heading">Portlet 8</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-primary">
              <div class="panel-heading">Portlet 9</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
      </div>
      <div class="col-md-3 column sortable">
      	<h3><?php echo $this->translate("Fechamento")?></h3>
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-default">
              <div class="panel-heading">Portlet 1</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-primary">
              <div class="panel-heading">Portlet 2</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
          <!-- BEGIN Portlet PORTLET-->
          <div class="panel panel-success">
              <div class="panel-heading">Portlet 3</div>
              <div class="panel-body">
                  Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.
                  Cras mattis consectetur purus sit amet fermentum. Duis mollis.
              </div>
          </div>
          <!-- END Portlet PORTLET-->
      </div>
  </div>
  <!-- page end-->
<?php 
$this->headScript()->prependFile($this->basePath("js/draggable-portlet.js"));
$this->headscript()->captureStart();
echo <<<JS
    jQuery(document).ready(function() {
      DraggablePortlet.init();
    });
JS;
$this->headscript()->captureEnd();
?>