<?php 
use Application\Services\SystemFunctions;

$this->headtitle($this->translate("Editar Endereços do Cliente"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("customer")?>"><?php echo $this->translate("Clientes") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar Endereços do Cliente") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>
 

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
                              <ul class="nav nav-tabs">
                                  <li>
                                      <a href="<?php echo $this->url("customer/edit", array("id"=>$customer->idCustomer))?>"><?php echo $this->translate("Editar Cliente")?></a>
                                  </li>
                                  <li class="active">
                                      <a data-toggle="tab"><?php echo $this->translate("Endereços")?></a>                                      
                                  </li>
                                  <li class="">
                                      <a><?php echo $this->translate("Contatos")?></a>                                      
                                  </li>
                                  <li class="">
                                      <a><?php echo $this->translate("Integrações")?></a>                                      
                                  </li>
                              </ul>
                          </header>
			<div class="panel-body">
					<?php if($customer->customerType==1){ ?>
					<div class="form-group">
						<div class="col-sm-12">
						<h4><?php echo $this->translate("Nome:")?>
							<?php echo $customerPerson->name." ".$customerPerson->last_name; ?></h4></div>
					</div>
					<?php }else{ ?>
					<div class="form-group">
						<div class="col-sm-12"><h4><?php echo $this->translate("Empresa:")?>
							<?php echo $customerCompany->social_name." (".$customerCompany->fantasy_name.")"; ?></h4>
						</div>
					</div>
					<?php } ?>
					<div class="form-group">
						
						<div id="address-list">
						
						</div>
						<?php if(count($addresses)<5){ ?>
						<div class="col-sm-12">
    						<div class="col-sm-3">
        						<div class="alert alert-success alert-block col-sm-12">
        							<h4><?php echo $this->translate("Vazio")?></h4>
        							<button data-toggle="modal" href="#add-address" class="btn btn-success"><?php echo $this->translate("Adicionar Endereço")?></button>
        						</div>
    						</div>
						</div>
						<?php } ?>
					</div>
			</div>
		</section>
	</div>
	<!-- NEW ADDRESS MODAL -->
	<div class="modal fade" id="add-address" tabindex="-1" role="dialog"
		aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal"
						aria-hidden="true">&times;</button>
					<h4 class="modal-title"><?php echo $this->translate("Cadastrar novo endereço")?></h4>
				</div>
				<form class="form-horizontal tasi-form" method="post" id="customerAddress" action="">
				
				<div class="modal-body">
					<input type="hidden" name="customer_id" value="<?php echo $customer->idCustomer; ?>">
    				<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Descrição*:")?></label>
						<div class="col-sm-10">
								<input type="text" name="name" maxlength="45" class="form-control" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Rua*:")?></label>
						<div class="col-sm-10">
								<input type="text" name="street" maxlength="60" class="form-control" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Número:")?></label>
						<div class="col-sm-4">
								<input type="text" name="house_number" maxlength="15" class="form-control">
						</div>
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Complemento:")?></label>
						<div class="col-sm-4">
								<input type="text" name="complement" maxlength="60" class="form-control">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Bairro:")?></label>
						<div class="col-sm-4">
								<input type="text" name="neighborhood" maxlength="60" class="form-control">
						</div>
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("CEP*:")?></label>
						<div class="col-sm-4">
								<input type="text" name="zip_code" maxlength="45" class="form-control" required>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("País*:")?></label>
						<div class="col-sm-10">
								<select name="country_id" id="country" required class="form-control">
									<option value="0"><?php echo $this->translate("Selecione")?></option>
									<?php foreach($countries as $country){ ?>
									<option value="<?php echo $country->countryId; ?>"><?php echo $country->name; ?></option>
									<?php } ?>
								</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Estado*:")?></label>
						<div class="col-sm-10">
								<select name="zone_id" id="zone" required class="form-control" disabled="disabled">
									<option value="0"><?php echo $this->translate("Selecione")?></option>
								</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Cidade*:")?></label>
						<div class="col-sm-10">
								<select name="city_id" id="city" required class="form-control" disabled="disabled">
									<option value="0"><?php echo $this->translate("Selecione")?></option>
								</select>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<button data-dismiss="modal" class="btn btn-default"
						type="button"><?php echo $this->translate("Cancelar")?></button>
					<button class="btn btn-success" type="submit"><?php echo $this->translate("Cadastrar")?></button>
				</div>
				</form>
			</div>
		</div>
	</div>
	<!-- END NEW ADDRESS MODAL -->
</div>
<?php 
$this->headscript()->captureStart();
$customerType = $customer->customerType;
$urlZones = $this->url('zones');
$urlCities = $this->url('cities');
$urlAddress = $this->url('customer/address', array("id"=>$customer->idCustomer));
$urlAddressList = $this->url('customer/address-list', array("id"=>$customer->idCustomer));

echo <<<JS
$(document).ready(function(){
    $("#address-list").load("$urlAddressList");
    //Carregar Estados
    $("#country").change(function(e){
    	$.post("$urlZones",
        {
            id: $("#country").val()
        },
        function(data, status){
            if(data!='error'){
            	$.each(JSON.parse(data),function(key, value) 
                {
                    $("#zone").append('<option value=' + value.id + '>' + value.name + '</option>');
                });
			    
			    $("#zone").removeAttr("disabled");
            }else{
    	        console.log("Ops, algo deu errado ao tentar carregar os Estados do País "+$("#country").val());
            }
        });
    });
    //Carregar Cidades
    $("#zone").change(function(e){
    	$.post("$urlCities",
        {
            id: $("#zone").val()
        },
        function(data, status){
            if(data!='error'){
                $('#city')
                    .empty()
                    .append('<option selected="selected" value="0">Selecione</option>')
                ;
            	$.each(JSON.parse(data),function(key, value) 
                {
                    $("#city").append('<option value=' + value.id + '>' + value.name + '</option>');
                });
			    
			    $("#city").removeAttr("disabled");
            }else{
    	        console.log("Ops, algo deu errado ao tentar carregar as Cidades do Estado "+$("#zone").val());
            }
        });
    });
    //Upload
    $("#customerAddress").submit(function(e){
    	e.preventDefault();
    	$.ajax({
            url: "$urlAddress",
      type: "POST",
      data:  new FormData(this),
      contentType: false,
            cache: false,
      processData:false,
      success: function(data){
       if(data=='error')
       {
        alert("Houve um erro ao validar os dados. Tente novamente.");
       }
       else
       {
        $("#customerAddress")[0].reset(); 
        $("#add-address").modal('toggle');
        $("#address-list").load("$urlAddressList");
       }
     },
    error: function(e){
       $("#err").html(e).fadeIn();
    }          
       });
    });
});
JS;
$this->headscript()->captureEnd();


$this->headScript()->prependFile($this->basePath("js/validators/customer.js"));
$this->headScript()->prependFile($this->basePath('assets/bootstrap-inputmask/bootstrap-inputmask.min.js'));
?>