<table class="table table-striped table-advance table-hover">
	<thead>
		<tr>
			<th><i class="fa fa-group"></i> <?php echo $this->translate("Descrição")?></th>
			<th><i class="fa fa-phone"></i> <?php echo $this->translate("Telefone")?></th>
			<th><i class="fa fa-envelope"></i> <?php echo $this->translate("E-mail ")?></th>
			<th><i class="fa fa-bookmark"></i> <?php echo $this->translate("Principal")?></th>
			<th><i class="fa fa-edit"></i> <?php echo $this->translate("Ações")?></th>
		</tr>
	</thead>
	<tbody>
				<?php
    
    foreach ($contacts as $contact) {
        if ($contact->principal) {
            $status = $this->translate("Sim");
            $statusClass = "success";
        } else {
            $status = $this->translate("Não");
            $statusClass = "danger";
        }
        ?>
					<tr>
			<td><?php echo $contact->desc; ?></td>
			<td><?php echo $contact->phone; ?></td>
			<td><a href="mailto:<?php echo $contact->email;?>"><?php echo $contact->email; ?></a></td>
			<td><span class="label label-<?php echo $statusClass; ?> label-mini"><?php echo $status; ?></span></td>
			<td><button
				class="btn btn-primary btn-xs edit"  data="<?php echo $contact->idContact; ?>"> <i class="fa fa-pencil"></i>
			</button>
				<button data="<?php echo $contact->idContact; ?>"
					class="btn btn-danger btn-xs delete">
					<i class="fa fa-trash-o "></i>
				</button></td>
		</tr>
					<?php } ?>
				</tbody>
</table>
<!-- EDIT CONTACT MODAL -->
<div class="modal fade" id="editContact" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title"><?php echo $this->translate("Editar contato")?></h4>
			</div>
			<form class="form-horizontal tasi-form" method="post" id="customerContactEdit" action="">			
				<div class="modal-body" id="formulario">
						<input name="idContact" id="idContact" value="" type="hidden">
						<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Descrição*:")?></label>
        					<div class="col-sm-10">
                              	<input name="desc" type="text" id="desc" value="" class="form-control" maxlength="255" required>
        					</div>
        				</div>
        				<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Telefone:")?></label>
        					<div class="col-sm-10">
                              	<input name="phone" type="tel" id="phone" value="" class="form-control" maxlength="20">
        					</div>
        				</div>
        				<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Email:")?></label>
        					<div class="col-sm-10">
                              	<input name="email" type="email" id="email" value="" class="form-control" maxlength="255">
        					</div>
        				</div>
        				<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Principal:")?></label>
        					<div class="col-sm-10">
                            	<input type="checkbox" name="principal" id="principal" value="1" data-toggle="switch" class="form-control"  /> 
        					</div>
        				</div>
				</div>
				<div class="modal-body" id="success" hidden="" >
					<div class="col-sm-4"></div>
					<div class="col-sm-4"><img src="<?php echo $this->basepath("img/success-icon.png")?>" width="200"></div>
					<div class="col-sm-4"></div>
					<div class="form-group">
					</div>
				</div>
				<div class="modal-footer">
					<button data-dismiss="modal" class="btn btn-default" type="button"><?php echo $this->translate("Sair")?></button>
					<button class="btn btn-success" type="submit" id="edit"><?php echo $this->translate("Salvar")?></button>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- END EDIT CONTACT MODAL -->
<?php 
$deleteUrl = $this->url("customer/contact-delete", array("id"=>$customer->idCustomer));
$editDataUrl = $this->url("customer/contact-edit", array("id"=>$customer->idCustomer));
$contactEditUrl = $this->url("customer/contact-edit", array("id"=>$customer->idCustomer));
$contactsUrl = $this->url("customer/contact-list", array("id"=>$customer->idCustomer));

$this->headScript()->captureStart();
echo <<<JS
$(document).ready(function(){
    $(".delete").click(function(e){
    	   var r = confirm("Você realmente deseja apagar esse contato?");
           if(r == true){
                $.ajax({
                      url: "$deleteUrl",
                      type: "POST",
                      data:  +$(this).attr("data"),
                      contentType: false,
                            cache: false,
                      processData:false,
                      success: function(data){
                           if(data=='success')
                           {
			                    location.reload();
                           }
                           else
                           {
                                alert("Houve um erro ao tentar cadastrar.");
                           }
            	      }
        		});    
            }else{
                alert("Cancelou");
            }
    });
    $(".edit").click(function(e){
        $('#editContact').modal('show');
	    var idContact = $(this).attr("data");
	    $.get("$editDataUrl", 
	    {
		  idContact: idContact
	    },
	    function(data, status){
		    var dados = JSON.parse(data);
		    if(data!='error'){
		        $('#idContact').val(dados["idContact"]);
                $('#desc').val(dados["desc"]);
			    $('#phone').val(dados["phone"]);
			    $('#email').val(dados["email"]);
			    if(dados["principal"]){
				    $('#principal').prop('checked', true);
			    }
		    }
        });
    });
    $("#customerContactEdit").submit(function(e){
        e.preventDefault();
        $.ajax({
              url: "$contactEditUrl",
              type: "POST",
              data:  new FormData(this),
              contentType: false,
                    cache: false,
              processData:false,
              success: function(data){
                   if(data=='success')
                   {
                        $("#formulario").hide();
        			    $("#edit").hide();
        			    $("#success").fadeIn(300);
					    //Dá um refresh na página
                        window.location.reload(true);
                   }
                   else
                   {
                        alert("Houve um erro ao tentar cadastrar.");
                   }
    	      }
		});    
    });
});
JS;
$this->headscript()->captureEnd();

?>