<?php
$this->headtitle($this->translate("Contatos do Cliente"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("customer")?>"><?php echo $this->translate("Clientes") ?></a></li>
			<li class="active"><?php echo $this->translate("Editar Endereços do Cliente") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>


<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
				<ul class="nav nav-tabs">
					<li><a
						href="<?php echo $this->url("customer/edit", array("id"=>$customer->idCustomer))?>"><?php echo $this->translate("Editar Cliente")?></a>
					</li>
					<li class=""><a href="<?php echo $this->url("customer/address", array("id"=>$customer->idCustomer))?>"><?php echo $this->translate("Endereços")?></a>
					</li>
					<li class="active"><a data-toggle="tab" ><?php echo $this->translate("Contatos")?></a></li>
					<li class=""><a><?php echo $this->translate("Integrações")?></a></li>
				</ul>
			</header>
			<div class="panel-body">
				<?php if($customer->customerType==1){ ?>
				<div class="form-group">
					<div class="col-sm-12">
						<h4><?php echo $this->translate("Nome:")?>
							<?php echo $customerPerson->name." ".$customerPerson->last_name; ?></h4>
					</div>
				</div>
				<?php }else{ ?>
				<div class="form-group">
					<div class="col-sm-12">
						<h4><?php echo $this->translate("Empresa:")?>
							<?php echo $customerCompany->social_name." (".$customerCompany->fantasy_name.")"; ?></h4>
					</div>
				</div>
				<?php } ?>
				<div class="col-sm-12">
			    	<hr>
			    	<button data-toggle="modal" href="#addContact" id="novo" class="btn btn-success"><?php echo $this->translate("Adicionar Contato")?></button>
			    	
			    </div>
			    <div class="col-sm-12">
    			    
				</div>
			</div>
		</section>
	</div>
</div>
<!-- NEW CONTACT MODAL -->
<div class="modal fade" id="addContact" tabindex="2" role="dialog"
	aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-hidden="true">&times;</button>
				<h4 class="modal-title"><?php echo $this->translate("Cadastrar novo contato")?></h4>
			</div>
			<form class="form-horizontal tasi-form" method="post" id="customerContactAdd" action="">
				<div class="modal-body" id="formulario">
        				<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Descrição*:")?></label>
        					<div class="col-sm-10">
                              	<input name="description" type="text" value="" class="form-control" maxlength="255" required>
        					</div>
        				</div>
        				<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Telefone:")?></label>
        					<div class="col-sm-10">
                              	<input name="phone" type="tel" value="" class="form-control" maxlength="20">
        					</div>
        				</div>
        				<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Email:")?></label>
        					<div class="col-sm-10">
                              	<input name="email" type="email" value="" class="form-control" maxlength="255">
        					</div>
        				</div>
        				<div class="form-group">
        					<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Principal:")?></label>
        					<div class="col-sm-10">
                            	<input type="checkbox" name="principal" value="1" data-toggle="switch" class="form-control"  /> 
        					</div>
        				</div>
				</div>
				<div class="modal-body" id="success" hidden="" >
					<div class="col-sm-4"></div>
					<div class="col-sm-4"><img src="<?php echo $this->basepath("img/success-icon.png")?>" width="200"></div>
					<div class="col-sm-4"></div>
					<div class="form-group">
					</div>
				</div>
				<div class="modal-footer">
					<button data-dismiss="modal" class="btn btn-default" type="button"><?php echo $this->translate("Sair")?></button>
					<button class="btn btn-success" type="submit" id="cadastrar"><?php echo $this->translate("Cadastrar")?></button>
				</div>
			</form>
		</div>
	</div>
</div>
<!-- END NEW CONTACT MODAL -->
<?php
$customerType = $customer->customerType;
$contactAddUrl = $this->url("customer/contact-add", array("id"=>$customer->idCustomer));

$this->headscript()->captureStart();
echo <<<JS
$(document).ready(function(){
    $("#novo").click(function(e){
        $("#customerContactAdd")[0].reset();
        $("#formulario").fadeIn();
	    $("#cadastrar").fadeIn();
        $("#success").hide();
    });
    $("#customerContactAdd").submit(function(e){
        e.preventDefault();
        $.post("$contactAddUrl", function(data, status){
			if(data=='success'){
			    $("#formulario").hide();
			    $("#cadastrar").hide();
			    $("#success").fadeIn(300);
		    }
            alert("ops"+data+" Status: "+status);
        });
    });
});
JS;
$this->headscript()->captureEnd();

$this->headScript()->prependFile($this->basePath("js/validators/customer.js"));
$this->headScript()->prependFile($this->basePath('assets/bootstrap-inputmask/bootstrap-inputmask.min.js'));
?>