<?php
use Application\Services\SystemFunctions;

$this->headtitle($this->translate("Clientes"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li class="active"><?php echo $this->translate("Clientes") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<div class="row">
	<div class="col-lg-6">
		<div class="input-group m-bot15">
          <span class="input-group-addon"><i class="fa fa-search"></i></span>
          <input type="text" class="form-control" placeholder="<?php echo $this->translate("Pesquisar")?>">
      </div>
	</div>
	<div class="col-lg-2">
		<select class="form-control input-md m-bot15">
              <option><?php echo $this->translate("Mais novos")?></option>
              <option><?php echo $this->translate("Mais antigos")?></option>
              <option><?php echo $this->translate("Ativos")?></option>
              <option><?php echo $this->translate("Inativos")?></option>
          </select>
	</div>
	<div class="col-lg-2">
		
		<button class="btn btn-default"><?php echo $this->translate("Procurar")?></button>
	</div>
	<?php if($permissions["insert"]){?>
	<div class="col-lg-2">
		<a href="<?php echo $this->url("customer/new")?>"
			class="btn btn-primary"><i class="fa fa-user"></i> <?php echo $this->translate("Novo Cliente")?></a>
	</div>
	<?php } ?>
</div>
<br>
<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading"> <?php echo $this->translate("Clientes")?></header>
			<table class="table table-striped table-advance table-hover">
				<thead>
					<tr>
						<th><i class="fa fa-user"></i> <?php echo $this->translate("Nome")?></th>
						<th><i class="fa fa-envelope"></i> <?php echo $this->translate("Email")?></th>
						<th><i class="fa fa-phone"></i> <?php echo $this->translate("Telefone")?></th>
						<th><i class="fa fa-map-signs"></i> <?php echo $this->translate("Cidade")?></th>
						<th><i class="fa fa-clock-o"></i> <?php echo $this->translate("Atualizado em")?></th>
						<th><i class="fa fa-circle-thin"></i> <?php echo $this->translate("Status")?></th>
						<th><i class="fa fa-edit"></i> <?php echo $this->translate("Ações")?></th>
					</tr>
				</thead>
				<tbody>
				<?php
    
    foreach ($customers as $customer) {
        if ($customer->active) {
            $status = $this->translate("Ativo");
            $statusClass = "success";
        } else {
            $status = $this->translate("Inativo");
            $statusClass = "danger";
        }
        ?>
					<tr>
						<td><?php //echo $customer->title; ?></td>
						<td><?php //echo $customer->description; ?></td>
						<td><?php //echo $customer->author; ?></td>
						<td><?php //echo SystemFunctions::dateInvert($customer->publicationDate, "brazilian"); ?></td>
						<td><?php //echo SystemFunctions::dateInvert($customer->lastUpdateDate, "brazilian"); ?></td>
						<td><span
							class="label label-<?php echo $statusClass; ?> label-mini"><?php echo $status; ?></span></td>
						<td>
							<a
							href="<?php echo $this->url("article/edit", array("id"=>$customer->idCustomer))?>"
							class="btn btn-primary btn-xs"> <i class="fa fa-pencil"></i>
						</a>
							<button data-toggle="modal" href="#delete-<?php echo $customer->idCustomer; ?>"
								class="btn btn-danger btn-xs">
								<i class="fa fa-trash-o "></i>
							</button>
						</td>
					</tr>
					<!-- EXCLUSION MODAL -->
					<div class="modal fade" id="delete-<?php echo $customer->idCustomer; ?>" tabindex="-1" role="dialog"
						aria-labelledby="myModalLabel" aria-hidden="true">
						<div class="modal-dialog">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal"
										aria-hidden="true">&times;</button>
									<h4 class="modal-title"><?php echo $this->translate("Desejas realmente excluir?")?></h4>
								</div>
								<div class="modal-body"><?php echo $this->translate("Você realmente deseja excluir <strong>".$customer->title."</strong> e todo o conteúdo relacionado com essa página?")?></div>
								<div class="modal-footer">
									<button data-dismiss="modal" class="btn btn-default"
										type="button"><?php echo $this->translate("Cancelar")?></button>
									<a href="<?php echo $this->url("article/delete", array("id"=>$customer->idCustomer))?>" class="btn btn-danger" type="button"><?php echo $this->translate("Excluir")?></a>
								</div>
							</div>
						</div>
					</div>
					<!-- END OF EXCLUSION MODAL -->
					<?php } ?>
				</tbody>
			</table>
		</section>
	</div>
</div>
