<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ImagesDatabase\Module'                        => __DIR__ . '/Module.php',
    'ImagesDatabase\Controller\ImagesDatabaseController' => __DIR__ . '/src/ImagesDatabase/Controller/ImagesDatabaseController.php',
 );
