<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ImagesDatabase\Module'                        => __DIR__ . '/Module.php',
    'ImagesDatabase\Controller\ImagesDatabaseController' => __DIR__ . '/src/ImagesDatabase/Controller/ImagesDatabaseController.php',
    'ImagesDatabaseTest\Framework\TestCase'        => __DIR__ . '/tests/ImagesDatabase/Framework/TestCase.php',
    'ImagesDatabaseTest\SampleTest'                => __DIR__ . '/tests/ImagesDatabase/SampleTest.php',
);
