<?php
use Zend\Session\Container;

$session = new Container('Auth');
$name = $session->__get('userName');
$idUser = $session->__get('idUser');
$idCompany = $session->__get('idCompany');
$websiteName = $session->__get('websiteName');
$websiteId = $session->__get('websiteId');
$l = 1;
foreach ($permissions as $permission) {
    $module[$l] = $permission->website_module_idModule;
    $l ++;
}
?>
<ul class="sidebar-menu" id="nav-accordion">

	<li><a class="active" href="<?php echo $this->url("home"); ?>"> <i
			class="fa fa-dashboard"></i> <span><?php echo $this->translate("Dashboard")?></span>
	</a></li>

	<?php
// Just users from the Comapny 1, TekSul, can access this module
if (array_search(1, $module)) {
    ?>
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-building"></i>
			<span><?php echo $this->translate("Empresas")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("company")?>"><?php echo $this->translate("Listar")?></a></li>
			<li><a href="<?php echo $this->url("company/new")?>"><?php echo $this->translate("Cadastrar")?></a></li>
		</ul></li>
	<?php
}
if (array_search(2, $module)) { // Websites ?>
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-laptop"></i>
			<span><?php echo $this->translate("Websites")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("website")?>"><?php echo $this->translate("Listar")?></a></li>
        	<?php
    // Just users from the Comapny 1, TekSul, can access this module
    if ($idCompany == 1) {
        ?>
			<li><a href="<?php echo $this->url("website/new")?>"><?php echo $this->translate("Cadastrar")?></a></li>		
			<?php } ?>		
		</ul></li>
	<?php } ?>
	
	<?php
if (array_search(9, $module)) { // Usuários ?>
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-users"></i>
			<span><?php echo $this->translate("Clientes")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("customer"); ?>"><?php echo $this->translate("Clientes") ?></a></li>
			<li><a href="<?php echo $this->url("customer/new"); ?>"><?php echo $this->translate("Novo Cliente") ?></a></li>
		</ul></li>
	<?php
}
?>
	<?php if(array_search(4, $module)){ ?>
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-picture-o"></i>
			<span><?php echo $this->translate("Banco de Imagens")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("images-database"); ?>"><?php echo $this->translate("Listar"); ?></a></li>
			<li><a href="calendar.html"><?php echo $this->translate("Cadastrar")?></a></li>
		</ul></li>
	<?php } ?>
		<?php if(array_search(5, $module)){ ?>
	
	<li class="sub-menu"><a href="javascript:;"> <i
			class="fa fa-file-text-o"></i> <span><?php echo $this->translate("Páginas")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("page"); ?>"><?php echo $this->translate("Listar") ?></a></li>
			<li><a href="advanced_form_components.html"><?php echo $this->translate("Nova") ?></a></li>
		</ul></li>
		<?php
}
?>
		
			<?php if(array_search(8, $module)){ //Check if the user already selected a website?>
		
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-file-text"></i>
			<span><?php echo $this->translate("Artigos")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("article"); ?>"><?php echo $this->translate("Artigos") ?></a></li>
			<li><a href="<?php echo $this->url("article/new"); ?>"><?php echo $this->translate("Novo Artigo") ?></a></li>
			<li><a href="<?php echo $this->url("category"); ?>"><?php echo $this->translate("Categorias") ?></a></li>
			<li><a href="<?php echo $this->url("category/new"); ?>"><?php echo $this->translate("Nova Categoria") ?></a></li>
		</ul></li>
	<?php
}
?>
<?php if(array_search(10, $module)){ ?>
		
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-cube"></i>
			<span><?php echo $this->translate("Produtos")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("product"); ?>"><?php echo $this->translate("Produtos") ?></a></li>
			<li><a href="<?php echo $this->url("product"); ?>"><?php echo $this->translate("Novo Produto") ?></a></li>
			<li><a href="<?php echo $this->url("product/category"); ?>"><?php echo $this->translate("Categorias") ?></a></li>
			<li><a href="<?php echo $this->url("product/category/new"); ?>"><?php echo $this->translate("Nova Categoria") ?></a></li>
		</ul></li>
	<?php
}
?>
<?php if(array_search(11, $module)){ ?>
		
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-shopping-cart"></i>
			<span><?php echo $this->translate("Pedidos")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("order"); ?>"><?php echo $this->translate("Pedidos") ?></a></li>
			<li><a href="<?php echo $this->url("order"); ?>"><?php echo $this->translate("Novo Pedido") ?></a></li>
			<li><a href="<?php echo $this->url("order"); ?>"><?php echo $this->translate("Meus Pedidos") ?></a></li>
		</ul></li>
	<?php
}
?>
		<?php if(array_search(6, $module)){ //Check if the user already selected a website?>
	
	<li class="sub-menu"><a href="<?php echo $this->url("conversor"); ?>">
			<i class="fa fa-th"></i> <span>Conversor</span>
	</a></li>
	<?php } ?>
		<?php if(array_search(7, $module)){ //Check if the user already selected a website?>
	
	<li class="sub-menu"><a href="<?php echo $this->url("webservices"); ?>">
			<i class="fa fa-cube"></i> <span>Webservices</span>
	</a></li>
	<!--multi level menu end-->
	
	<?php }
	if (array_search(3, $module)) {
    ?>
	<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-user"></i>
			<span><?php echo $this->translate("Usuários")?></span>
	</a>
		<ul class="sub">
			<li><a href="<?php echo $this->url("user")?>"><?php echo $this->translate("Listar")?></a></li>
			<li><a href="<?php echo $this->url("user/new")?>"><?php echo $this->translate("Cadastrar")?></a></li>
		</ul></li>
	<?php } ?>

</ul>
<!-- sidebar menu end-->