<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Pipeline\Module'                        => __DIR__ . '/Module.php',
    'Pipeline\Controller\PipelineController' => __DIR__ . '/src/Pipeline/Controller/PipelineController.php',
    'PipelineTest\Framework\TestCase'        => __DIR__ . '/tests/Pipeline/Framework/TestCase.php',
    'PipelineTest\SampleTest'                => __DIR__ . '/tests/Pipeline/SampleTest.php',
);
