<?php 
$this->headtitle($this->translate("Excluir Página"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("company")?>"><?php echo $this->translate("Páginas") ?></a></li>
			<li class="active"><?php echo $this->translate("Exclusão") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php 
if($message["flag"]>0){
    if($message["flag"]==1){
        $class = "success";
    }else{
        $class = "danger";
    }
    ?>
    <div class="alert alert-<?php echo $class; ?> alert-block fade in">
    	<button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>
    	<p><?php echo $message["message"]?></p>
    	<br>
    	<a href="<?php echo $this->url("page") ?>" class="btn btn-round btn-default"><i class="fa fa-undo"></i>&nbsp;<?php echo $this->translate("Voltar")?> </a>
    </div>
    <?php
}
?>

