<?php 
$this->headtitle($this->translate("Nova Cor"));
?>
<div class="row">
	<div class="col-lg-12">
		<!--breadcrumbs start -->
		<ul class="breadcrumb">
			<li><a href="<?php echo $this->url("application"); ?>"><i
					class="fa fa-home"></i> <?php echo $this->translate("Home") ?></a></li>
			<li><a href="<?php echo $this->url("product")?>"><?php echo $this->translate("Produtos") ?></a></li>
			<li><a href="<?php echo $this->url("product/category")?>"><?php echo $this->translate("Cores") ?></a></li>
			<li class="active"><?php echo $this->translate("Nova") ?></li>
		</ul>
		<!--breadcrumbs end -->
	</div>
</div>

<?php 
if($message["flag"]>0){
    if($message["flag"]==1){
        $class = "success";
    }else{
        $class = "danger";
    }
    ?>
    <div class="alert alert-<?php echo $class; ?> alert-block fade in">
    	<button data-dismiss="alert" class="close close-sm" type="button"><i class="fa fa-times"></i></button>
    	<p><?php echo $message["message"]?></p>
    </div>
    <?php
}
?>

<div class="row">
	<div class="col-lg-12">
		<section class="panel">
			<header class="panel-heading tab-bg-dark-navy-blue ">
                              <ul class="nav nav-tabs">
                                  <li class="active">
                                      <a data-toggle="tab" href="#"><?php echo $this->translate("Nova Cor")?></a>
                                  </li>
                              </ul>
                          </header>
			<div class="panel-body">
				<form class="form-horizontal tasi-form" method="post" id="color" enctype="multipart/form-data">
					<div class="form-group" id="language">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Idioma")?></label>
						<div class="col-sm-10">
                        	<select name="language_id" class="form-control">
                        		<?php foreach($languages as $language){ ?>
								<option value="<?php echo $language->idLanguage; ?>"><?php echo $language->name;?></option>
								<?php } ?>
							</select>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Nome da cor*")?></label>
						<div class="col-sm-10">
                        	<input type="text" class="form-control" name="name" id="name" maxlength="60" value="<?php echo $color->name; ?>" >
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 col-sm-2 control-label"><?php echo $this->translate("Cor*")?></label>
						<div class="col-sm-10">
                              <input type="text" name="hexa" class="colorpicker-default form-control" value="" />
						</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-2"><?php echo $this->translate("Imagem da Cor")?></label>
                          <div class="col-md-10">
                              <div class="fileupload fileupload-new" data-provides="fileupload">
                                  <div class="fileupload-new thumbnail" style="width: 100px; height: 100px;">
                                      <img src="http://www.placehold.it/100x100/EFEFEF/AAAAAA&amp;text=no+image" alt="" />
                                  </div>
                                  <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 100px; max-height: 100px; line-height: 20px;"></div>
                                  <div>
                                   <span class="btn btn-white btn-file">
                                   <span class="fileupload-new"><i class="fa fa-paper-clip"></i> <?php echo $this->translate("Selecione a Imagem")?></span>
                                   <span class="fileupload-exists"><i class="fa fa-undo"></i> <?php echo $this->translate("Mudar")?></span>
                                   <input type="file" class="default" name="image" />
                                   </span>
                                      <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> <?php echo $this->translate("Remover")?></a>
                                  </div>
                              </div>
                              <span class="label label-danger"><?php echo $this->translate("Nota")?></span>
                             <span>
                             <?php echo $this->translate("Se o código hexadecimal não for o suficiente, adicione uma imagem que represente a cor. Tamanho recomendado: 100x100px")?>
                             </span>
                          </div>
					</div>
					<div class="form-group">
						&nbsp;&nbsp;<button type="submit" class="btn btn-info"><?php echo $this->translate("Cadastrar")?></button>
						&nbsp;<a href="<?php echo $this->url("product/color")?>" class="btn btn-danger"><?php echo $this->translate("Voltar")?></a>
					</div>
				</form>
			</div>
		</section>
	</div>
</div>
<?php 
$this->headlink()->prependStylesheet($this->basePath('assets/bootstrap-colorpicker/css/colorpicker.css'));
$this->headlink()->prependStylesheet($this->basePath('assets/bootstrap-fileupload/bootstrap-fileupload.css'));


$this->headScript()->prependFile($this->basePath("js/validators/product-color.js"));
$this->headScript()->prependFile($this->basePath('assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js'));
$this->headScript()->prependFile($this->basePath('assets/bootstrap-fileupload/bootstrap-fileupload.js'));

$this->headscript()->captureStart();
echo <<<JS
//colorpicker start

$('.colorpicker-default').colorpicker({
    format: 'hex'
});
JS;
$this->headscript()->captureEnd();
?>


