<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Webservices\Module'                        => __DIR__ . '/Module.php',
    'Webservices\Controller\PageController' => __DIR__ . '/src/Webservices/Controller/PageController.php',
    'WebservicesTest\Framework\TestCase'        => __DIR__ . '/tests/Webservices/Framework/TestCase.php',
    'WebservicesTest\SampleTest'                => __DIR__ . '/tests/Webservices/SampleTest.php',
);
